name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: list files
        run: ls -la
      
      - name: lint code
        run: npm run lint

      - name: run type checker
        run: npm run typecheck

      - name: run tests
        run: echo "No tests yet"
      
      - name: build project
        run: npm run build
